### PR TITLE
Add millisecond granularity for sqlite date handling

### PR DESCRIPTION
**Pull request by kinigitbyday**

### CODE REVIEW

**Comment by jakeswenson** [comment]
Lgtm, might be nice to add a test though....

**Comment by kinigitbyday** [comment]
@jakeswenson good call. Discovered that the actual format TypeORM uses was not quite the same as what I had, so the `OrEqual` operators were still not working right. 

That led me to find the `DateUtlis` functions in TypeORM which appear to be exactly what's needed.

**Comment by jakeswenson** [comment]
With a test this seems mergable without the @devshorts stamp of approval... 😉 would be good to hear from him though!

**Review by devshorts — APPROVED** [review]
Welcome back. I knew leap year would provide

**Pull request merged**
